"use client";

import { useEffect, useState } from "react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { CheckCircle2, XCircle } from "lucide-react";
import { api, type CausalGraphResponse, type FeatureImportanceItem, type ModelInfo } from "@/lib/api";
import { CausalGraphView } from "@/components/CausalGraphView";

const MODEL_COLORS: Record<string, string> = {
  Accuracy: "#4f46e5",
  "ROC-AUC": "#db2777",
};

export default function InsightsPage() {
  const [modelInfo, setModelInfo] = useState<ModelInfo | null>(null);
  const [graph, setGraph] = useState<CausalGraphResponse | null>(null);
  const [importance, setImportance] = useState<FeatureImportanceItem[] | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    Promise.all([api.modelInfo(), api.causalGraph(), api.featureImportance()])
      .then(([m, g, i]) => {
        setModelInfo(m);
        setGraph(g);
        setImportance(i);
      })
      .catch((e) => setError(String(e)));
  }, []);

  const modelChartData = modelInfo
    ? Object.entries(modelInfo.metrics).map(([name, m]) => ({
        name,
        Accuracy: Number((m["Accuracy"] * 100).toFixed(2)),
        "ROC-AUC": Number((m["ROC-AUC"] * 100).toFixed(2)),
      }))
    : [];

  const importanceChartData = (importance ?? [])
    .filter((i) => i.shap_importance !== null)
    .slice(0, 10)
    .map((i) => ({
      feature: i.feature,
      "SHAP importance": Number((i.shap_importance ?? 0).toFixed(4)),
      "Causal score": Number((i.causal_score ?? 0).toFixed(4)),
    }));

  return (
    <div className="mx-auto max-w-6xl px-4 py-12 sm:px-6">
      <h1 className="text-3xl font-bold tracking-tight">Model &amp; causal insights</h1>
      <p className="mt-2 max-w-2xl text-muted">
        Everything below is generated by <code className="rounded bg-surface px-1.5 py-0.5 text-xs">python -m
        ml.pipeline</code> and served live from the FastAPI backend.
      </p>

      {error && (
        <div className="mt-6 rounded-xl border border-malignant/30 bg-malignant/10 px-4 py-3 text-sm text-malignant">
          {error} &mdash; is the backend running at NEXT_PUBLIC_API_URL?
        </div>
      )}

      <section className="mt-10">
        <h2 className="text-lg font-semibold">Model comparison</h2>
        <div className="mt-4 h-80 rounded-2xl border border-border bg-surface p-4">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={modelChartData}>
              <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
              <XAxis dataKey="name" tick={{ fontSize: 12 }} stroke="var(--muted)" />
              <YAxis domain={[80, 100]} tick={{ fontSize: 12 }} stroke="var(--muted)" />
              <Tooltip contentStyle={{ background: "var(--surface)", border: "1px solid var(--border)" }} />
              <Legend />
              <Bar dataKey="Accuracy" fill={MODEL_COLORS["Accuracy"]} radius={[4, 4, 0, 0]} />
              <Bar dataKey="ROC-AUC" fill={MODEL_COLORS["ROC-AUC"]} radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </section>

      <section className="mt-12">
        <h2 className="text-lg font-semibold">Feature importance</h2>
        <p className="mt-1 text-sm text-muted">
          Statistical causal score (screening heuristic) vs. SHAP importance (model-specific explanation).
        </p>
        <div className="mt-4 h-96 rounded-2xl border border-border bg-surface p-4">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={importanceChartData} layout="vertical" margin={{ left: 20 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
              <XAxis type="number" tick={{ fontSize: 12 }} stroke="var(--muted)" />
              <YAxis dataKey="feature" type="category" width={140} tick={{ fontSize: 11 }} stroke="var(--muted)" />
              <Tooltip contentStyle={{ background: "var(--surface)", border: "1px solid var(--border)" }} />
              <Legend />
              <Bar dataKey="SHAP importance" fill="#ef4444" radius={[0, 4, 4, 0]} />
              <Bar dataKey="Causal score" fill="#8b5cf6" radius={[0, 4, 4, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </section>

      <section className="mt-12">
        <h2 className="text-lg font-semibold">Causal graph</h2>
        <p className="mt-1 text-sm text-muted">
          Domain-informed DAG. Red node is the outcome; edges into it are the treatments evaluated below.
        </p>
        {graph && (
          <div className="mt-4">
            <CausalGraphView nodes={graph.nodes} edges={graph.edges} />
          </div>
        )}
      </section>

      <section className="mt-12 mb-4">
        <h2 className="text-lg font-semibold">Backdoor-adjusted causal effects</h2>
        <p className="mt-1 text-sm text-muted">
          Standardized average treatment effect on malignancy, estimated with DoWhy and stress-tested with
          placebo/random-common-cause refutation.
        </p>
        <div className="mt-4 overflow-x-auto rounded-2xl border border-border bg-surface">
          <table className="w-full text-left text-sm">
            <thead className="border-b border-border text-xs uppercase text-muted">
              <tr>
                <th className="px-4 py-3">Treatment</th>
                <th className="px-4 py-3">Standardized ATE</th>
                <th className="px-4 py-3">Adjustment set</th>
                <th className="px-4 py-3">Robust to placebo</th>
              </tr>
            </thead>
            <tbody>
              {graph?.effects.map((e) => (
                <tr key={e.treatment} className="border-b border-border last:border-0">
                  <td className="px-4 py-3 font-medium">{e.treatment}</td>
                  <td className="px-4 py-3 tabular-nums">{e.standardized_ate.toFixed(4)}</td>
                  <td className="max-w-md px-4 py-3 text-xs text-muted">{e.adjustment_set}</td>
                  <td className="px-4 py-3">
                    {e.robust_to_placebo ? (
                      <span className="inline-flex items-center gap-1 text-benign">
                        <CheckCircle2 size={14} /> yes
                      </span>
                    ) : (
                      <span className="inline-flex items-center gap-1 text-malignant">
                        <XCircle size={14} /> no
                      </span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}
